### ISSUE TITLE
Mod actions

### ISSUE THREAD

**Issue by GarfieldsPipe** [KushBlazingJudah/feditext#2]
How do I login to the admin panel? How do I create a board and manage its settings?

**Comment by GarfieldsPipe** [comment]
If I do `./feditext create -username admin -password mypass123 -priv 2` and go to /admin/login and enter the credetenials it gives an "Unauthorized" error.

**Comment by KushBlazingJudah** [comment]
I am able to login with that exact command on an empty database, do you have `randadmin` in your configuration set to true?
If so, remove the `randadmin` line from your configuration and try once more. `randadmin` doesn't respect existing data and will replace it upon startup.

> How do I create a board and manage its settings?

There is no dedicated view for board management, it's done exclusively from `/admin` for now.
You can create/update board settings from the first three textboxes you see, to update a board simply reuse the board's ID and it will use the new values in the title and description textboxes.
Do not use forward slashes around the ID. The ID is also limited to alphanumeric characters, it will complain otherwise.
Use whatever you want for the rest of it.

To follow boards, you can use the textboxes down by the "Following" header.
Use the board's ID as the board, and the target is what you want to follow. If I have `/prog/`, its ID is `prog`. If I want to follow `http://foo.example.com/prog`, I fill in `prog` for the board and `http://foo.example.com/prog` as the target.
Do this on another instance to receive posts from the other board. Continuing with the example, we can see posts made on `foo.example.com/prog` but they can't see posts from us until they follow us.

I will eventually get around to writing a small piece of documentation for how to use the admin side of things once I clean that page up in the coming days, since I just wired up the bare minimum to get it working.

**Comment by GarfieldsPipe** [comment]
> I am able to login with that exact command on an empty database, do you have `randadmin` in your configuration set to true? If so, remove the `randadmin` line from your configuration and try once more. `randadmin` doesn't respect existing data and will replace it upon startup.
Even completely removing that line, restarting the server and executing the command doesn't solve the problem. Still getting an "Unauthorized" error.

**Comment by KushBlazingJudah** [comment]
The privilege level is stored in a token sent to the client signed by the server, and that is used to determine the privileges someone has. Did you successfully authenticate when a user's privileges was 0?
If so, you need to remove the `token` cookie and log in once more. This is a side effect of how authentication is done.

**Comment by GarfieldsPipe** [comment]
I've tried again just now with a clean reinstalled server and the latest version and the problem still occurs. Something is definitely broken in the code.

**Comment by KushBlazingJudah** [comment]
I'm afraid that I still cannot reproduce this, also on a clean slate.
I've pushed some changes to the `dev` branch which pretties up auth errors and makes them more descriptive, could you update to that and try once again?
I still think something is wrong with the privileges level you receive, so it should now at the very least spit out what level you are and what level you need to be to access something.
Again, the only time you will go to `/admin` and get `Unauthorized` is when you access that as a janitor.

**Comment by GarfieldsPipe** [comment]
It now says "An error has occurred
You must be authenticated to access this page."

Again, the credentials (which I made by executing ./feditext create -username admin2 -password mypass123 -priv 2) are fine because otherwise it would say something like Invalid credentials.

**Comment by KushBlazingJudah** [comment]
Do you not have cookies enabled?

**Comment by GarfieldsPipe** [comment]
> Do you not have cookies enabled? Does your browser's devtools mention anything about the cookie in the console, is it visible in storage?

I do have cookies enabled in my browser but the site doesn't set any cookies, not after the login (attempt) either.

**Comment by KushBlazingJudah** [comment]
I've finally been able to reproduce it, and I think I found the root cause of it (`secure` attribute of cookies). I'll fix it.
`secure` is ignored when the host is localhost, and I guess Tor Browser also ignores it in the case of onions because I was able to login to my instance over Tor without any issue. I'll enable `secure` if it is being served over HTTPS.

**Comment by KushBlazingJudah** [comment]
Try the latest commit in master.

**Comment by GarfieldsPipe** [comment]
> Try the latest commit in master.

Yup works now, cheers.
